"""add a new field 'master_id' to the booking

Revision ID: 282133febf23
Revises: 093fa13cd4de
Create Date: 2025-01-31 12:30:56.662823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "282133febf23"
down_revision: Union[str, None] = "093fa13cd4de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("master_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_bookings_master_id"), "bookings", ["master_id"], unique=False
    )
    op.create_foreign_key(
        None, "bookings", "masters", ["master_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.drop_index(op.f("ix_bookings_master_id"), table_name="bookings")
    op.drop_column("bookings", "master_id")
    # ### end Alembic commands ###
