"""delete referrals table

Revision ID: 2bce71b48048
Revises: 858cd275ee2d
Create Date: 2025-02-23 08:48:15.136179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2bce71b48048"
down_revision: Union[str, None] = "858cd275ee2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("referrals")
    op.add_column(
        "subscriptions", sa.Column("start_date", sa.DateTime(), nullable=True)
    )
    op.add_column("subscriptions", sa.Column("end_date", sa.DateTime(), nullable=False))
    op.add_column(
        "subscriptions", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.drop_column("subscriptions", "expires_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("subscriptions", "updated_at")
    op.drop_column("subscriptions", "end_date")
    op.drop_column("subscriptions", "start_date")
    op.create_table(
        "referrals",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "referrer_master_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "referred_master_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["referred_master_id"],
            ["users.id"],
            name="referrals_referred_master_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["referrer_master_id"],
            ["users.id"],
            name="referrals_referrer_master_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="referrals_pkey"),
    )
    # ### end Alembic commands ###
