"""update relationship

Revision ID: 34a0a7101e28
Revises: 733cda946c67
Create Date: 2025-02-15 10:31:50.103463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a0a7101e28'
down_revision: Union[str, None] = '733cda946c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_master_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['master_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('business_info_master_id_fkey', 'business_info', type_='foreignkey')
    op.create_foreign_key(None, 'business_info', 'users', ['master_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dates_master_id_fkey', 'dates', type_='foreignkey')
    op.create_foreign_key(None, 'dates', 'users', ['master_id'], ['id'], ondelete='CASCADE')
    op.add_column('feedbacks', sa.Column('master_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'feedbacks', 'users', ['master_id'], ['id'])
    op.drop_constraint('services_master_id_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'users', ['master_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_master_association_master_id_fkey', 'user_master_association', type_='foreignkey')
    op.drop_constraint('user_master_association_user_id_fkey', 'user_master_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_master_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_master_association', 'users', ['master_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_master_association', type_='foreignkey')
    op.drop_constraint(None, 'user_master_association', type_='foreignkey')
    op.create_foreign_key('user_master_association_user_id_fkey', 'user_master_association', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_master_association_master_id_fkey', 'user_master_association', 'masters', ['master_id'], ['id'])
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_master_id_fkey', 'services', 'masters', ['master_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_column('feedbacks', 'master_id')
    op.drop_constraint(None, 'dates', type_='foreignkey')
    op.create_foreign_key('dates_master_id_fkey', 'dates', 'masters', ['master_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'business_info', type_='foreignkey')
    op.create_foreign_key('business_info_master_id_fkey', 'business_info', 'masters', ['master_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_master_id_fkey', 'bookings', 'masters', ['master_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
