"""change link

Revision ID: 3d3fe9bca6c2
Revises: 4683f0f0ef98
Create Date: 2025-02-25 14:17:57.448381

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d3fe9bca6c2"
down_revision: Union[str, None] = "4683f0f0ef98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("subscription_plan_id", sa.Integer(), nullable=False)
    )
    op.drop_index("ix_payments_subscription_id", table_name="payments")
    op.create_index(
        op.f("ix_payments_subscription_plan_id"),
        "payments",
        ["subscription_plan_id"],
        unique=False,
    )
    op.drop_constraint("payments_subscription_id_fkey", "payments", type_="foreignkey")
    op.create_foreign_key(
        None, "payments", "subscription_plans", ["subscription_plan_id"], ["id"]
    )
    op.drop_column("payments", "subscription_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("subscription_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.create_foreign_key(
        "payments_subscription_id_fkey",
        "payments",
        "subscriptions",
        ["subscription_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_payments_subscription_plan_id"), table_name="payments")
    op.create_index(
        "ix_payments_subscription_id", "payments", ["subscription_id"], unique=False
    )
    op.drop_column("payments", "subscription_plan_id")
    # ### end Alembic commands ###
