"""update tables

Revision ID: 4683f0f0ef98
Revises: 877a154d9ca6
Create Date: 2025-02-25 13:00:56.131874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4683f0f0ef98"
down_revision: Union[str, None] = "877a154d9ca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payments", "payment_method", existing_type=sa.VARCHAR(), nullable=True
    )
    op.add_column(
        "subscription_plans", sa.Column("description", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_plans", "description")
    op.alter_column(
        "payments", "payment_method", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
