"""delete field 'transaction_id' and update 'status' field

Revision ID: 5f88b99ceda4
Revises: 3d3fe9bca6c2
Create Date: 2025-03-02 12:09:15.709007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5f88b99ceda4"
down_revision: Union[str, None] = "3d3fe9bca6c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payments",
        "status",
        existing_type=postgresql.ENUM(
            "pending", "completed", "failed", name="payment_status"
        ),
        type_=sa.String(),
        nullable=True,
    )
    op.drop_constraint("payments_transaction_id_key", "payments", type_="unique")
    op.drop_column("payments", "transaction_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("transaction_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint(
        "payments_transaction_id_key", "payments", ["transaction_id"]
    )
    op.alter_column(
        "payments",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM("pending", "completed", "failed", name="payment_status"),
        nullable=False,
    )
    # ### end Alembic commands ###
