"""Edit and add  new column

Revision ID: 733cda946c67
Revises: add98606e782
Create Date: 2025-02-04 10:19:21.624554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "733cda946c67"
down_revision: Union[str, None] = "add98606e782"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("reminder_time", sa.DateTime(), nullable=True))
    op.add_column("bookings", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.drop_column("bookings", "reminder_hours")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("reminder_hours", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("bookings", "updated_at")
    op.drop_column("bookings", "reminder_time")
    # ### end Alembic commands ###
