"""update tables

Revision ID: 858cd275ee2d
Revises: d69d21447735
Create Date: 2025-02-15 16:43:20.870824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "858cd275ee2d"
down_revision: Union[str, None] = "d69d21447735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.drop_index("ix_bookings_active", table_name="bookings")
    op.create_index(
        op.f("ix_bookings_is_active"), "bookings", ["is_active"], unique=False
    )
    op.drop_column("bookings", "active")
    op.add_column(
        "business_info", sa.Column("phone_number", sa.String(length=13), nullable=False)
    )
    op.drop_column("business_info", "phone")
    op.add_column("dates", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column(
        "dates", sa.Column("deactivation_time", sa.DateTime(), nullable=False)
    )
    op.add_column("dates", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.drop_index("ix_dates_active", table_name="dates")
    op.create_index(op.f("ix_dates_is_active"), "dates", ["is_active"], unique=False)
    op.drop_column("dates", "del_time")
    op.drop_column("dates", "active")
    op.add_column("services", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.drop_index("ix_services_active", table_name="services")
    op.create_index(
        op.f("ix_services_is_active"), "services", ["is_active"], unique=False
    )
    op.drop_column("services", "active")
    op.add_column("times", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("times", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.drop_index("ix_times_active", table_name="times")
    op.create_index(op.f("ix_times_is_active"), "times", ["is_active"], unique=False)
    op.drop_column("times", "active")
    op.add_column("users", sa.Column("phone_number", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.drop_constraint("users_phone_key", "users", type_="unique")
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_unique_constraint(None, "users", ["phone_number"])
    op.drop_column("users", "phone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("phone", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.create_unique_constraint("users_phone_key", "users", ["phone"])
    op.drop_column("users", "created_at")
    op.drop_column("users", "is_active")
    op.drop_column("users", "phone_number")
    op.add_column(
        "times", sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_times_is_active"), table_name="times")
    op.create_index("ix_times_active", "times", ["active"], unique=False)
    op.drop_column("times", "created_at")
    op.drop_column("times", "is_active")
    op.add_column(
        "services",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_services_is_active"), table_name="services")
    op.create_index("ix_services_active", "services", ["active"], unique=False)
    op.drop_column("services", "is_active")
    op.add_column(
        "dates", sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "dates",
        sa.Column(
            "del_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_dates_is_active"), table_name="dates")
    op.create_index("ix_dates_active", "dates", ["active"], unique=False)
    op.drop_column("dates", "created_at")
    op.drop_column("dates", "deactivation_time")
    op.drop_column("dates", "is_active")
    op.add_column(
        "business_info",
        sa.Column("phone", sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    )
    op.drop_column("business_info", "phone_number")
    op.add_column(
        "bookings",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_bookings_is_active"), table_name="bookings")
    op.create_index("ix_bookings_active", "bookings", ["active"], unique=False)
    op.drop_column("bookings", "is_active")
    # ### end Alembic commands ###
