"""update the 'services' table

Revision ID: 8d13e67aaeb6
Revises: d86d3dba6028
Create Date: 2025-01-24 16:27:12.837382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8d13e67aaeb6"
down_revision: Union[str, None] = "d86d3dba6028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("services", sa.Column("active", sa.Boolean(), nullable=True))
    op.add_column("services", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("services", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_services_active"), "services", ["active"], unique=False)
    op.drop_column("services", "duration")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services",
        sa.Column(
            "duration", postgresql.INTERVAL(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_services_active"), table_name="services")
    op.drop_column("services", "updated_at")
    op.drop_column("services", "created_at")
    op.drop_column("services", "active")
    # ### end Alembic commands ###
