"""Changed the 'admin' column to 'role' in the User model

Revision ID: a7a6a705ffe9
Revises: 56aa2a2ce437
Create Date: 2025-01-16 15:23:56.494548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7a6a705ffe9"
down_revision: Union[str, None] = "56aa2a2ce437"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.String(length=10), nullable=True))
    op.drop_column("users", "admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("admin", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###
