"""update masters

Revision ID: add98606e782
Revises: 282133febf23
Create Date: 2025-02-03 15:16:17.025944

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add98606e782"
down_revision: Union[str, None] = "282133febf23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("masters", sa.Column("user_id", sa.Integer(), nullable=True))
    op.drop_constraint("masters_phone_key", "masters", type_="unique")
    op.create_unique_constraint(None, "masters", ["user_id"])
    op.create_foreign_key(
        None, "masters", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("masters", "name")
    op.drop_column("masters", "phone")
    op.add_column("users", sa.Column("phone", sa.String(length=13), nullable=True))
    op.create_unique_constraint(None, "users", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "phone")
    op.add_column(
        "masters",
        sa.Column("phone", sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    )
    op.add_column(
        "masters",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "masters", type_="foreignkey")
    op.drop_constraint(None, "masters", type_="unique")
    op.create_unique_constraint("masters_phone_key", "masters", ["phone"])
    op.drop_column("masters", "user_id")
    # ### end Alembic commands ###
