"""delete 'working_hours'

Revision ID: b54bf44a3d1c
Revises: 5f88b99ceda4
Create Date: 2025-03-06 12:27:20.509569

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b54bf44a3d1c"
down_revision: Union[str, None] = "5f88b99ceda4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("business_info", "working_hours")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "business_info",
        sa.Column("working_hours", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
