"""change column 'name_id' to 'user_id' in the model User

Revision ID: bb65fa75ab3f
Revises: a7a6a705ffe9
Create Date: 2025-01-18 16:52:07.751848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb65fa75ab3f"
down_revision: Union[str, None] = "a7a6a705ffe9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("user_id", sa.Integer(), nullable=True))
    op.drop_constraint("bookings_name_id_fkey", "bookings", type_="foreignkey")
    op.create_foreign_key(
        None, "bookings", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("bookings", "name_id")
    op.create_unique_constraint(None, "dates", ["date"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "dates", type_="unique")
    op.add_column(
        "bookings",
        sa.Column("name_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.create_foreign_key(
        "bookings_name_id_fkey",
        "bookings",
        "users",
        ["name_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("bookings", "user_id")
    # ### end Alembic commands ###
