"""add 'master_id to 'Time''

Revision ID: c2ff2370a090
Revises: b54bf44a3d1c
Create Date: 2025-03-07 09:18:27.026237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2ff2370a090"
down_revision: Union[str, None] = "b54bf44a3d1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("times", sa.Column("master_id", sa.Integer(), nullable=True))
    op.drop_index("ix_times_date_id", table_name="times")
    op.create_index(op.f("ix_times_master_id"), "times", ["master_id"], unique=False)
    op.create_foreign_key(
        None, "times", "users", ["master_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "times", type_="foreignkey")
    op.drop_index(op.f("ix_times_master_id"), table_name="times")
    op.create_index("ix_times_date_id", "times", ["date_id"], unique=False)
    op.drop_column("times", "master_id")
    # ### end Alembic commands ###
