"""add new column 'Time'

Revision ID: d06ad542ca17
Revises: bb65fa75ab3f
Create Date: 2025-01-21 15:48:33.151350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd06ad542ca17'
down_revision: Union[str, None] = 'bb65fa75ab3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['date_id'], ['dates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_times_active'), 'times', ['active'], unique=False)
    op.add_column('bookings', sa.Column('time_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'times', ['time_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bookings', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'time_id')
    op.drop_index(op.f('ix_times_active'), table_name='times')
    op.drop_table('times')
    # ### end Alembic commands ###
