"""create a new table 'business_info'

Revision ID: d1191c8c8d04
Revises: d06ad542ca17
Create Date: 2025-01-22 09:34:37.188999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1191c8c8d04"
down_revision: Union[str, None] = "d06ad542ca17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("address", sa.String(length=60), nullable=False),
        sa.Column("phone", sa.String(length=13), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("working_hours", sa.JSON(), nullable=False),
        sa.Column("google_maps_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("business_info")
    # ### end Alembic commands ###
