"""add 'is_active' to 'subscription_plans'

Revision ID: efe0b87d3a90
Revises: c2ff2370a090
Create Date: 2025-03-13 12:27:23.449030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efe0b87d3a90"
down_revision: Union[str, None] = "c2ff2370a090"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription_plans", sa.Column("is_active", sa.Boolean(), nullable=True)
    )
    op.create_index(
        op.f("ix_subscription_plans_is_active"),
        "subscription_plans",
        ["is_active"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_subscription_plans_is_active"), table_name="subscription_plans"
    )
    op.drop_column("subscription_plans", "is_active")
    # ### end Alembic commands ###
