"""update tables

Revision ID: f4a5d4142c5d
Revises: 8d13e67aaeb6
Create Date: 2025-01-28 11:24:58.565922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4a5d4142c5d"
down_revision: Union[str, None] = "8d13e67aaeb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "masters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=13), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "user_master_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("master_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["masters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "master_id"),
    )
    op.add_column(
        "business_info", sa.Column("google_maps_link", sa.String(), nullable=True)
    )
    op.add_column(
        "business_info", sa.Column("telegram_link", sa.String(), nullable=True)
    )
    op.add_column(
        "business_info", sa.Column("instagram_link", sa.String(), nullable=True)
    )
    op.add_column("business_info", sa.Column("master_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_business_info_master_id"), "business_info", ["master_id"], unique=False
    )
    op.create_foreign_key(
        None, "business_info", "masters", ["master_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("business_info", "google_maps_url")
    op.add_column("dates", sa.Column("active", sa.Boolean(), nullable=True))
    op.add_column("dates", sa.Column("master_id", sa.Integer(), nullable=True))
    op.drop_constraint("dates_date_key", "dates", type_="unique")
    op.drop_index("ix_dates_free", table_name="dates")
    op.create_index(op.f("ix_dates_active"), "dates", ["active"], unique=False)
    op.create_index(op.f("ix_dates_master_id"), "dates", ["master_id"], unique=False)
    op.create_foreign_key(
        None, "dates", "masters", ["master_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("dates", "free")
    op.add_column("services", sa.Column("master_id", sa.Integer(), nullable=True))
    op.alter_column(
        "services",
        "price",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.drop_constraint("services_name_key", "services", type_="unique")
    op.create_index(
        op.f("ix_services_master_id"), "services", ["master_id"], unique=False
    )
    op.create_foreign_key(
        None, "services", "masters", ["master_id"], ["id"], ondelete="CASCADE"
    )
    op.create_index(op.f("ix_times_date_id"), "times", ["date_id"], unique=False)
    op.drop_constraint("times_date_id_fkey", "times", type_="foreignkey")
    op.create_foreign_key(
        None, "times", "dates", ["date_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "times", type_="foreignkey")
    op.create_foreign_key("times_date_id_fkey", "times", "dates", ["date_id"], ["id"])
    op.drop_index(op.f("ix_times_date_id"), table_name="times")
    op.drop_constraint(None, "services", type_="foreignkey")
    op.drop_index(op.f("ix_services_master_id"), table_name="services")
    op.create_unique_constraint("services_name_key", "services", ["name"])
    op.alter_column(
        "services",
        "price",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("services", "master_id")
    op.add_column(
        "dates", sa.Column("free", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "dates", type_="foreignkey")
    op.drop_index(op.f("ix_dates_master_id"), table_name="dates")
    op.drop_index(op.f("ix_dates_active"), table_name="dates")
    op.create_index("ix_dates_free", "dates", ["free"], unique=False)
    op.create_unique_constraint("dates_date_key", "dates", ["date"])
    op.drop_column("dates", "master_id")
    op.drop_column("dates", "active")
    op.add_column(
        "business_info",
        sa.Column("google_maps_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "business_info", type_="foreignkey")
    op.drop_index(op.f("ix_business_info_master_id"), table_name="business_info")
    op.drop_column("business_info", "master_id")
    op.drop_column("business_info", "instagram_link")
    op.drop_column("business_info", "telegram_link")
    op.drop_column("business_info", "google_maps_link")
    op.drop_table("user_master_association")
    op.drop_table("masters")
    # ### end Alembic commands ###
